apiVersion: v1
kind: Service
metadata:
  name: voicevox
  namespace: voicevox
  labels:
    app: voicevox
    app.kubernetes.io/name: voicevox
    app.kubernetes.io/part-of: voicevox
spec:
  type: ClusterIP
  selector:
    app: voicevox
  ports:
    - name: http
      port: 50021
      targetPort: 50021
