---
apiVersion: bitnami.com/v1alpha1
kind: SealedSecret
metadata:
  name: tunnel-credentials
  namespace: cloudflare
spec:
  encryptedData:
    credentials.json: AgCirtQTNGX9xV7IySOX8oGTc5DtNkpjiGxsoTtx+58g97/z7j2k3WMnbxEG4goOS/wXd6AMzwNkyfWjapryZQl2Roij3zNXMtiQthqB8r9xLRi/lHFVWIRmJs14DTTSa4w5HCFxTrxPmCnW0JdjcfqdN1j9EHp8+eA8aoXVFb2rsIoEhSaDJaSsRKxIrHjGI6G6eJdNacGXvOaifT0IdDE0D6CXA3Fp1DGAgHEka3wnl6pg4ZrEOc1lYiHFVxBv2JeA+gb9DybqWlYiHbtfuW/wW7VCmpwMi8wNknocLCmovDTAr2f254I2KaTNoyGojZPuEgcaqu+9n/vP7jEiuXXVbJklC1v2w92tcYNC98gVKn/N3nmoa48hgrwwdQ1SrwrOLv6M9GekiOHqYMhTarhJbCJtvvmv1GDxIM8GgXnmshwwg0/4BKnYrCD711q246rz+n/jfg+fRnJRCg+90oildfFHnDSsMc1vtBwakr+5vxjh5bfDUXZ5a8lLbMS20jFWcvRkAi2xJeVqm7X0+3x6YFrEiSIMYq4fNz2PhulX/mIBb5CTXmTJMH3KyDZYAgKbpzOBQOiVcb5uWdXDcfyn+hpwMT4oupCzmndJvacH91pR6C6A4Y6cM2D1NAIwBLJKlbjCuaN0pNoIxJpOtkVnDfq516c6mXuPDPgo6ptwt00jWmTjfkZA429pBge6HcUldR4lhJ8666xxx7t9d9xgVhaqi3CcCpKXLD9Me6PRcWkPVhIOr5PrHWVV3QpP63NPHH0Ie2WLy2qpXH13X/9VEkHwkxPjJ8xrIgm5tBgtYNNIRfvYLplNJi9g+V64Zx35PoIX4PfmNZ8Er02ubzqzCAdFvf+43A7ajRug29288EuWEoHT41GhE5aFbHzcC2LcytYV/46dofZcPB4goem/2mC8/sDntH6nCuO3NgvZ
  template:
    metadata:
      name: tunnel-credentials
      namespace: cloudflare
    type: Opaque
