{{- if .Values.hpa.enabled }}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ .Values.resourceNames.hpa }}
  namespace: {{ .Values.instance.namespace }}
  labels:
    app: misskey
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ .Values.resourceNames.deployment }}
  minReplicas: {{ .Values.hpa.minReplicas }}
  maxReplicas: {{ .Values.hpa.maxReplicas }}
  metrics:
    - type: Resource
      resource:
        name: cpu
        target:
          type: AverageValue
          averageValue: {{ .Values.hpa.cpuAverageValue }}
  behavior:
    scaleUp:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleUp.stabilizationWindowSeconds }}
      policies:
        - type: Pods
          value: {{ .Values.hpa.scaleUp.podsValue }}
          periodSeconds: {{ .Values.hpa.scaleUp.periodSeconds }}
    scaleDown:
      stabilizationWindowSeconds: {{ .Values.hpa.scaleDown.stabilizationWindowSeconds }}
      policies:
        - type: Pods
          value: {{ .Values.hpa.scaleDown.podsValue }}
          periodSeconds: {{ .Values.hpa.scaleDown.periodSeconds }}
{{- end }}
